Drawer 메뉴창 디자인 및 기능 구현
Ji-InPark/KULEUM_BRIDGE pull request #15
Opened 2022-04-11 00:24 UTC by Kimhojoon1

디자인 및 기능 구현입니다. 다른 프로젝트에서는 적용이 되나, 본 프로젝트에서 Mainactivity에 onCreate 함수에 적용이 안되는데, 추후 방법을 찾아보도록 하겠습니다

2022-04-11 01:14 UTC, Ji-InPark requested changes
화면이 없어서 어떤지 잘 모르겠네요. 화면 첨부 부탁해요~

2022-04-11 01:14 UTC, Ji-InPark commented on KuleumBridge/app/src/main/java/com/KonDuckJoa/kuleumbridge/Grade/GradeAllList.java
> +    public static void setGradeAllInfo() {
code convention 지켜주세요

2022-04-11 01:14 UTC, Ji-InPark commented on KuleumBridge/app/src/main/java/com/KonDuckJoa/kuleumbridge/Grade/GradeAllList.java
> +            for (int i = 0; i < UserInfo.getInstance().getGradeAll().size(); i++) {
code convention 지켜주세요

2022-04-11 04:29 UTC, Ji-InPark commented on KuleumBridge/app/src/main/java/com/KonDuckJoa/kuleumbridge/Activity/DrawerActivity.java
> +
id하고 title 사용하는 부분이 저 if 문 밖에 없는 거 같은데 굳이 변수에 할당하지 않아도 될거 같아요

2022-04-11 04:29 UTC, Ji-InPark commented on KuleumBridge/app/src/main/java/com/KonDuckJoa/kuleumbridge/Activity/DrawerActivity.java
> +        }
case가 하나밖에 없는데 switch를 쓸 이유가 있을까요?

2022-04-11 04:29 UTC, Ji-InPark commented on KuleumBridge/app/src/main/java/com/KonDuckJoa/kuleumbridge/Grade/GradeAllList.java
> +    //Arraylist 성적 초기화
필요없는 주석 제거

2022-04-11 11:43 UTC, Ji-InPark requested changes
그리고 버튼 구현에 필요한 콜백 함수가 onCreate() 라면 fragment의 onCreate()를 사용해보세요.

2022-04-11 11:43 UTC, Ji-InPark commented on KuleumBridge/app/src/main/java/com/KonDuckJoa/kuleumbridge/Activity/DrawerActivity.java
> +
이런 공백은 하나만 놔주세요.

2022-04-11 11:43 UTC, Ji-InPark commented on KuleumBridge/app/src/main/java/com/KonDuckJoa/kuleumbridge/Activity/DrawerActivity.java
> +
여기도 공백은 하나만 놔주세요. 아래에 있는 공백들도 고쳐주세요

2022-04-11 11:43 UTC, Ji-InPark commented on KuleumBridge/app/src/main/java/com/KonDuckJoa/kuleumbridge/Activity/DrawerActivity.java
> +            public boolean onNavigationItemSelected(MenuItem menuItem) {
code convention 지켜주세요 (중괄호 위치) 
https://www.notion.so/ji-in/3-Declarations-e7104a4dc844481bbeea1056c8e19248#01756498e9f443c19afb2a174869a841

2022-04-11 11:43 UTC, Ji-InPark commented on KuleumBridge/app/src/main/java/com/KonDuckJoa/kuleumbridge/Activity/MainActivity.java
> +
사용안하는 import문이네요 지워주세요. 

이렇게 수정은 했지만 필요하지 않은 부분은 discard하거나 commit에 포함하지 말고 올려주세요

2022-04-12 04:22 UTC, Mingyu0626 approved these changes
Well done

2022-04-12 06:55 UTC, Kimhojoon1 commented on KuleumBridge/app/src/main/java/com/KonDuckJoa/kuleumbridge/Activity/MainActivity.java
> +
완료

2022-04-12 06:55 UTC, Kimhojoon1 commented on KuleumBridge/app/src/main/java/com/KonDuckJoa/kuleumbridge/Activity/DrawerActivity.java
> +
완료

2022-04-12 06:55 UTC, Kimhojoon1 commented on KuleumBridge/app/src/main/java/com/KonDuckJoa/kuleumbridge/Grade/GradeAllList.java
> +    //Arraylist 성적 초기화
완료

2022-04-12 07:02 UTC, Kimhojoon1 commented on KuleumBridge/app/src/main/java/com/KonDuckJoa/kuleumbridge/Grade/GradeAllList.java
> +    public static void setGradeAllInfo() {
완료

2022-04-12 07:08 UTC, Kimhojoon1 commented on KuleumBridge/app/src/main/java/com/KonDuckJoa/kuleumbridge/Grade/GradeAllList.java
> +            for (int i = 0; i < UserInfo.getInstance().getGradeAll().size(); i++) {
완료

2022-04-12 07:55 UTC, Kimhojoon1 commented on KuleumBridge/app/src/main/java/com/KonDuckJoa/kuleumbridge/Activity/DrawerActivity.java
> +
완료

2022-04-12 07:56 UTC, Kimhojoon1 commented on KuleumBridge/app/src/main/java/com/KonDuckJoa/kuleumbridge/Activity/DrawerActivity.java
> +            public boolean onNavigationItemSelected(MenuItem menuItem) {
완료

2022-04-12 08:15 UTC, Ji-InPark commented on KuleumBridge/app/src/main/java/com/KonDuckJoa/kuleumbridge/Activity/DrawerActivity.java
> +                return true;
switch문에 break 없어도 잘 돌아가나요?

2022-04-12 08:15 UTC, Ji-InPark commented on KuleumBridge/app/src/main/java/com/KonDuckJoa/kuleumbridge/Activity/DrawerActivity.java
> +    public boolean onOptionsItemSelected(MenuItem item) {
convention

2022-04-12 08:15 UTC, Ji-InPark commented on KuleumBridge/app/src/main/java/com/KonDuckJoa/kuleumbridge/Activity/MainActivity.java
> +
필요없는 공백 제거

2022-04-12 08:24 UTC, Ji-InPark approved these changes
수고하셨습니다~

컨플릭 해결하시고 머지해주세요

2022-04-12 08:56 UTC, merged