add setTimeTable() in MainActivity and timeTable_Layout in home_layou…
Ji-InPark/KULEUM_BRIDGE pull request #3
Opened 2022-03-22 02:43 UTC by Mingyu0626

시간표 레이아웃을 추가하고, MainActivity에 setTimeTable() 함수를 추가했습니다.
현재 setTimeTable()에는 파싱된 정보를 시간표 배열에 넣어주는 기능이 구현되지 않은 상태입니다.
또한 18교시 이후엔 1교시당 시간배치가 불규칙한 점을 고려하지 않았는데, 최대한 빨리 고쳐보도록 하겠습니다.

2022-03-22 12:16 UTC, Ji-InPark requested changes
리뷰 반영 부탁드려요~~

그리고 코드좀 보기 좋게 고친 것도 올려드릴테니 pull 하고 작업해주세요~

2022-03-22 12:16 UTC, Ji-InPark commented on KuleumBridge/app/src/main/java/com/KonDuckJoa/kuleumbridge/Activity/MainActivity.java
> +
동적으로 시간표를 그려주는 것 같은데 왜 미리 그리지 않고 runtime에 그리나요?

2022-03-22 12:16 UTC, Ji-InPark commented on KuleumBridge/app/src/main/java/com/KonDuckJoa/kuleumbridge/Activity/MainActivity.java
> +                        tv.setLayoutParams(new TableRow.LayoutParams(0,ViewGroup.LayoutParams.WRAP_CONTENT,0.4f));
다 똑같은 일을 하는 것 같은데 차이점이 뭔가요?

2022-03-22 12:16 UTC, Ji-InPark commented on KuleumBridge/app/src/main/java/com/KonDuckJoa/kuleumbridge/Activity/MainActivity.java
> +    public void setTimeTable(TableLayout table) {
첫화면이 홈화면이 아니라 시간표 화면이 나오네요 개정 부탁드려요~

그리고 원래 시간표는 홈화면에 넣는 걸로 알고 있었는데 사용자 정보 아래에 넣는 것은 어려운가요?

2022-03-23 08:08 UTC, Mingyu0626 commented
시간표 위치 및 생성 방식 변경 완료.

2022-03-24 13:49 UTC, wonniiii approved these changes

2022-03-24 13:50 UTC, wonniiii approved these changes

2022-04-04 00:24 UTC, Kimhojoon1 approved these changes

2022-05-04 13:00 UTC, closed without merging