스와이프 기능 구현
Ji-InPark/KULEUM_BRIDGE pull request #6
Opened 2022-03-26 17:10 UTC by Mingyu0626

메인 탭(홈,공지사항, 맛집, 성적 조회) 스와이프 기능을 구현했습니다. 
이 과정에서 MainActivity에 존재했던 각종 메소드들을 사용처에 맞는 Fragment 파일로 옮겨줆으로써 
MainAcitivty가 훨씬 깔끔해졌습니다. 
추가적으로 MainActivity에 남아있는 각종 버튼클릭(BtnClick) 메소드들 또한 Fragment 파일로 옮겨줄 계획입니다.

2022-03-26 17:17 UTC, wonniiii approved these changes
고생하셨습니다 - ! お疲れ様でした。

2022-03-27 15:34 UTC, Ji-InPark requested changes
리뷰 반영해주세요~

2022-03-27 15:34 UTC, Ji-InPark commented on KuleumBridge/app/src/main/java/com/KonDuckJoa/kuleumbridge/Activity/MainActivity.java
> +
이런 이름은 앞으로 길더라도 tabViewpagerBinding과 같이 적는걸로 바꿔나갑시다.

binding만 보고는 이게 무슨 변수인지 한 번에 알기가 힘들거든요.

2022-03-27 15:34 UTC, Ji-InPark commented on KuleumBridge/app/src/main/java/com/KonDuckJoa/kuleumbridge/Activity/MainActivity.java
> +        tabs.setupWithViewPager(viewPager);
이것도요 앞으로는 tabs보다는 tabLayout 그대로 적는게 좋아보입니다.

아니면 그 변수가 확실하게 어떤역할을 하는 건지 표현할 수 있는 이름도 좋습니다.

2022-03-27 15:34 UTC, Ji-InPark commented on KuleumBridge/app/src/main/java/com/KonDuckJoa/kuleumbridge/Activity/SectionsPagerAdapter.java
> +        return fragments[position];
딱봐도 어떤역할을 하는지 보이는 함수에 있는 주석은 제거해주세요.

2022-03-27 15:34 UTC, Ji-InPark commented on KuleumBridge/app/src/main/java/com/KonDuckJoa/kuleumbridge/Notice/NoticeInfoClass.java
> +*/
얘도 필요없어 보이긴 하지만 일단 냅둔거라 본인 판단하에 지워주세요.

2022-03-27 15:34 UTC, Ji-InPark commented on KuleumBridge/app/src/main/java/com/KonDuckJoa/kuleumbridge/fragment/gradeCheckFragment.java
>  import com.KonDuckJoa.kuleumbridge.R;
필요없는 import 문 정리 (alt + enter 눌러서 정리하면 편함)

2022-03-27 15:34 UTC, Ji-InPark commented on KuleumBridge/app/src/main/java/com/KonDuckJoa/kuleumbridge/fragment/gradeCheckFragment.java
> +    }
공백처리 잘해주세요

이런식으로 공백이 적절한 문맥에 따라서 있어야 가독성이 올라갑니다.

```java
public View onCreateView(LayoutInflater inflater, ViewGroup container,
                             Bundle savedInstanceState) {
        View view = inflater.inflate(R.layout.grade_check_layout,container,false);
        gradeNowSuccess(view);

        return view;
    }
```

2022-03-27 15:34 UTC, Ji-InPark commented on KuleumBridge/app/src/main/java/com/KonDuckJoa/kuleumbridge/fragment/gradeCheckFragment.java
> +                    textView.setSelected(true);
이렇게 중복되는 부분은 함수화 해서 어떤 역할을 하는지 명확하게 해주는 것이 더 좋습니다.

예를 들어 textView를 리턴하는 createTextViewWithSettings() 라는 함수를 만들면 어떤 일을 하는지 명확하게 보이니깐요.

2022-03-27 15:34 UTC, Ji-InPark commented on KuleumBridge/app/src/main/java/com/KonDuckJoa/kuleumbridge/fragment/homeFragment.java
> +        return view;
위와 마찬가지로 공백처리

2022-03-27 15:34 UTC, Ji-InPark commented on KuleumBridge/app/src/main/java/com/KonDuckJoa/kuleumbridge/fragment/homeFragment.java
> +        System.out.println("editStudentID 실행");
이런 print문을 사용한 디버깅은 앞으로 자제해주세요.

2022-03-27 15:34 UTC, Ji-InPark commented on KuleumBridge/app/src/main/java/com/KonDuckJoa/kuleumbridge/fragment/homeFragment.java
> +        TextView birthday = view.findViewById(R.id.studentCard_birthday_sep);
여기 변수 이름들을 더 명확하게 바꿀 수 있을 것 같아요. 그리고 앞으로 menu는 정확하게 menu를 뜻하는 상황 빼고는 지양합시다.

ex) TextView nameTextView

2022-03-27 15:34 UTC, Ji-InPark commented on KuleumBridge/app/src/main/java/com/KonDuckJoa/kuleumbridge/fragment/noticeFragment.java
> +    private Button noticeBtn;
추후에 사용할 버튼을 미리 만들어둔건가요?

미리 만들어둔 버튼을 커밋에 포함해서 올리는 것은 좋지 않습니다. 다음부터는 지양해주세요~

2022-03-27 15:34 UTC, Ji-InPark commented on KuleumBridge/app/src/main/java/com/KonDuckJoa/kuleumbridge/fragment/noticeFragment.java
> +
이 함수 이름과 하는 일이 다른 것 같은데 확인부탁드려요~~

2022-03-27 15:34 UTC, Ji-InPark commented on KuleumBridge/app/src/main/java/com/KonDuckJoa/kuleumbridge/fragment/noticeFragment.java
> +        return view;
여기도 공백 처리

2022-03-27 15:34 UTC, Ji-InPark commented on KuleumBridge/app/src/main/java/com/KonDuckJoa/kuleumbridge/fragment/noticeFragment.java
> +                tv.setSelected(true);
여기도 함수화해주세요~

2022-03-27 15:34 UTC, Ji-InPark commented on KuleumBridge/app/src/main/java/com/KonDuckJoa/kuleumbridge/fragment/noticeFragment.java
> +                    ViewGroup.LayoutParams.MATCH_PARENT, ViewGroup.LayoutParams.WRAP_CONTENT));
그리고 tbr, tv 같은 변수명 사용은 지양해주세요~

2022-03-27 15:34 UTC, Ji-InPark commented on KuleumBridge/app/src/main/java/com/KonDuckJoa/kuleumbridge/fragment/noticeFragment.java
> +    private void noticeTabListener(View view) {
함수명이 변수명 같이 보이네요. 변경 부탁드립니다.

2022-03-27 15:34 UTC, Ji-InPark commented on KuleumBridge/app/src/main/java/com/KonDuckJoa/kuleumbridge/fragment/noticeFragment.java
> +        tabLayout_notice.setTabTextColors(Color.parseColor("#000000"),Color.parseColor("#000000"));
여기도 함수화하면 좋겠죠?

2022-03-27 15:34 UTC, Ji-InPark commented on KuleumBridge/app/src/main/java/com/KonDuckJoa/kuleumbridge/fragment/noticeFragment.java
> +                // tab의 상태가 선택 상태로 변경
이런 필요없는 주석들은 모두 제거해주세요

2022-03-27 15:34 UTC, Ji-InPark commented on KuleumBridge/app/src/main/java/com/KonDuckJoa/kuleumbridge/fragment/noticeFragment.java
> +    private void changeTabNotice(int index, View view) {
index를 selectedIndex 와 같이 바꾼다면 아래에 있는 주석들을 지워도 될 거 같아요~

2022-03-27 15:34 UTC, Ji-InPark commented on KuleumBridge/app/src/main/java/com/KonDuckJoa/kuleumbridge/fragment/tastePlaceFragment.java
> +        return view;
```java
return inflater.inflate(R.layout.taste_place_layout,container,false);
```
로 쓸 수 있음

2022-03-28 06:27 UTC, Kimhojoon1 commented
お疲れ様でした~~

2022-03-29 13:26 UTC, Mingyu0626 commented on KuleumBridge/app/src/main/java/com/KonDuckJoa/kuleumbridge/Activity/MainActivity.java
> +
tabViewPagerBinding으로 변수명 변경 완료.

2022-03-29 13:26 UTC, Mingyu0626 commented on KuleumBridge/app/src/main/java/com/KonDuckJoa/kuleumbridge/Activity/MainActivity.java
> +        tabs.setupWithViewPager(viewPager);
mainTab으로 변수명 변경 완료.

2022-03-29 13:26 UTC, Mingyu0626 commented on KuleumBridge/app/src/main/java/com/KonDuckJoa/kuleumbridge/Activity/SectionsPagerAdapter.java
> +        return fragments[position];
제거 완료.

2022-03-29 13:27 UTC, Mingyu0626 commented on KuleumBridge/app/src/main/java/com/KonDuckJoa/kuleumbridge/Notice/NoticeInfoClass.java
> +*/
없애면 또 까먹을 우려가 있어 남겨두기로 결정.

2022-03-29 13:27 UTC, Mingyu0626 commented on KuleumBridge/app/src/main/java/com/KonDuckJoa/kuleumbridge/fragment/gradeCheckFragment.java
>  import com.KonDuckJoa.kuleumbridge.R;
모든 파일 정리 완료.

2022-03-29 13:28 UTC, Mingyu0626 commented on KuleumBridge/app/src/main/java/com/KonDuckJoa/kuleumbridge/fragment/noticeFragment.java
> +    private void noticeTabListener(View view) {
addOnNoticeTabSelectedListener()로 함수명 변경 완료.

2022-03-29 13:28 UTC, Mingyu0626 commented on KuleumBridge/app/src/main/java/com/KonDuckJoa/kuleumbridge/fragment/noticeFragment.java
> +        tabLayout_notice.setTabTextColors(Color.parseColor("#000000"),Color.parseColor("#000000"));
setNoticeTabColor()로 함수화 완료.

2022-03-29 13:28 UTC, Mingyu0626 commented on KuleumBridge/app/src/main/java/com/KonDuckJoa/kuleumbridge/fragment/noticeFragment.java
> +                // tab의 상태가 선택 상태로 변경
제거 완료.

2022-03-29 13:28 UTC, Mingyu0626 commented on KuleumBridge/app/src/main/java/com/KonDuckJoa/kuleumbridge/fragment/noticeFragment.java
> +    private void changeTabNotice(int index, View view) {
반영 완료.

2022-03-29 13:28 UTC, Mingyu0626 commented on KuleumBridge/app/src/main/java/com/KonDuckJoa/kuleumbridge/fragment/tastePlaceFragment.java
> +        return view;
반영 완료.

2022-03-29 14:03 UTC, Ji-InPark commented on KuleumBridge/app/src/main/java/com/KonDuckJoa/kuleumbridge/Activity/SectionsPagerAdapter.java
> +        fragments[0] = new HomeFragment();
init 줄임말말고 initialize와 같이 적어주세요~

2022-03-29 14:03 UTC, Ji-InPark commented on KuleumBridge/app/src/main/java/com/KonDuckJoa/kuleumbridge/Fragment/NoticeFragment.java
> +    private void NoticeSuccess(View view, String notice_category)
camel 케이스로 바꿔주세요~

2022-04-03 04:02 UTC, Mingyu0626 commented on KuleumBridge/app/src/main/java/com/KonDuckJoa/kuleumbridge/Activity/MainActivity.java
> +        Intent intentTastePlace = new Intent(this, TastePlaceList.class);
onTasteButtonClick 메소드는 onClick 메소드로 합치면 코드 길이만 괜히 더 늘어날거 같아서 그대로 뒀습니다

2022-04-03 04:02 UTC, Mingyu0626 commented on KuleumBridge/app/src/main/java/com/KonDuckJoa/kuleumbridge/Activity/MainActivity.java
> +            case R.id.grade_all_check_button: // 성적조회 레이아웃의 "세부 성적 조회" 버튼 상호작용 함수
주석 복붙하고 고치지를 않았네요 바꿀게요

2022-04-03 05:48 UTC, Ji-InPark approved these changes
전체적으로 많이 좋아졌네요 나머지 자잘한 부분은 같이 보완해나가죠

2022-04-03 05:48 UTC, Ji-InPark commented on KuleumBridge/app/src/main/res/layout/home_layout.xml
> +            android:id="@+id/you_have_4"
나중에 이런 id 이름에 대한것도 한 번 같이 고민해보시죠

2022-04-03 05:54 UTC, Mingyu0626 commented on KuleumBridge/app/src/main/res/layout/home_layout.xml
> +            android:id="@+id/you_have_4"
좋네요 내친김에 id컨벤션도 함 만들죠

2022-04-03 05:55 UTC, merged